{% set name = "cairocffi" %}
{% set version = "1.7.0" %}

package:
  name: cairocffi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7761863603894305f3160eca68452f373433ca8745ab7dd445bd2c6ce50dcab7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - cffi >=1.1
    - cairo >=1.14
    - pytest-runner
    - flit-core
  run:
    - python >=3.7
    - cffi >=1.1
    - cairo >=1.14

test:
  imports:
    - cairocffi

about:
  home: https://github.com/Kozea/cairocffi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: cffi-based cairo bindings for Python

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
