{% set name = "cairocffi" %}
{% set version = "0.8.0" %}
{% set sha256 = "65f21e6786e2b255ab1d3fda53a365a3565bb1808cabbbe59d99a797c61d3545" %}

package:
  name: cairocffi
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - dlopen-patch.linux.txt  # [linux]
    - dlopen-patch.osx.txt  # [osx]

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.1.0
    - cairo 1.14.*
  run:
    - python
    - cffi >=1.1.0
    - cairo 1.14.*

test:
  imports:
    - cairocffi

about:
  home: https://github.com/SimonSapin/cairocffi
  license: BSD 3-Clause
  summary: 'cffi-based cairo bindings for Python'
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
