{% set name = "cairocffi" %}
{% set version = "1.0.2" %}
{% set sha256 = "60485cf89ab0fdfc0446be53407b54da81c64f097fd52f12493b8375035b1445" %}

package:
  name: cairocffi
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Kozea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - dlopen-patch.linux.txt  # [linux]
    - dlopen-patch.osx.txt  # [osx]

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.1.0
    - cairo 1.14.*
  run:
    - python
    - cffi >=1.1.0
    - cairo 1.14.*

test:
  imports:
    - cairocffi

about:
  home: https://github.com/SimonSapin/cairocffi
  license: BSD 3-Clause
  summary: 'cffi-based cairo bindings for Python'
  license_family: BSD

extra:
  recipe-maintainers:
    - johanneskoester
