{% set name = "cairocffi" %}
{% set version = "1.1.0" %}

package:
  name: cairocffi
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1c0c5878f74ac9ccb5d48b2601fcc75390c881ce476e79f4cfedd288b1b05db

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.5
    - pip
    - cffi >=1.1
    - cairo >=1.14
    - pytest-runner
  run:
    - python >=3.5
    - cffi >=1.1
    - cairo >=1.14

test:
  imports:
    - cairocffi

about:
  home: https://github.com/Kozea/cairocffi
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'cffi-based cairo bindings for Python'

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
